version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitor-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - monitor-net

  grafana-alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    command: ["run", "/etc/alloy/agent.alloy"]
    volumes:
      - ./agent.alloy:/etc/alloy/agent.alloy
    restart: unless-stopped
    networks:
      - monitor-net


networks:
  monitor-net:
    external: true