version: '3.8'

services:
  app:
    image: php-mysql-app:latest
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
