version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  grafana-agent:
    image: grafana/agent:v0.40.3  # legacy config support
    container_name: grafana-agent
    volumes:
      - ../monitoring/grafana-agent.yaml:/etc/grafana-agent.yaml
    command: ["--config.file=/etc/grafana-agent.yaml"]
    environment:
      - GRAFANA_BEARER_TOKEN=${GRAFANA_BEARER_TOKEN}
    restart: unless-stopped
