version: '3.8'

services:
  app:
    image: ${IMAGE_URI}
    environment:
      DB_HOST: db
      DB_NAME: testdb
      DB_USER: root
      DB_PASS: example
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  dbdata:
