version: '3.8'

services:
  app:
    image: php-mysql-app:latest
    build:
      context: ../.
    environment:
      DB_HOST: db
      DB_NAME: optimy_db
      DB_USER: root
      DB_PASS: example
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./init.sql:/var/www/html/init.sql

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
