version: '3.8'

services:
  app:
    image: ${IMAGE_URI}
    build:
      context: ..
      dockerfile: Dockerfile
    image: your-ecr-repo/php-app:${TAG:-latest}
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
