name: Lint CloudFormation Templates

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Run linter
        run: |
          find cloudformation -name "*.yml" -o -name "*.yaml" | xargs -I {} cfn-lint {} || true
